ls:
    .dir: kebab-case
    .ts: kebab-case

ignore:
    - .git
    - .github
    - __MACOSX
    - "**/__MACOSX"
    - .DS_Store
    - "**/.DS_Store"
    - node_modules
    - "**/node_modules"
    - dist
    - "**/dist"
    - apis
    - "**/@types"
    - "**/.expo"
    - "**/expo-env.d.ts"
    - "**/.next"
    - "**/next-env.d.ts"
    - "**/.panda"
    - "*.tsbuildinfo"
    - "**/*.tsbuildinfo"
    - "**/*.log"
    - "**/pnpm-debug.log*"
