[files]
extend-exclude = [
    ".git/",
    ".github/",
    "__MACOSX/",
    ".DS_Store",
    "node_modules/",
    "dist/",
    "apis/",
    ".expo/",
    "expo-env.d.ts",
    ".next/",
    "next-env.d.ts",
    ".panda",
    "*.tsbuildinfo",
    "*.log",
    "pnpm-debug.log*",
]
